version: "3.7"
services:
  app:
    build: ./app
    image: app:dev
    networks:
      - client
    depends_on:
      - db
    environment:
      NODE_ENV: development
    env_file: .env
    volumes:
      - ./app:/app/app
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    ports:
      - "8080:8080"
    command: npm run dev
  db:
    build: ./db
    image: mysql:dev
    networks:
      client:
        aliases:
          - db
    restart: always
    env_file: .env
    volumes:
      - ./db/dbdata:/var/lib/mysql
      - ./db/populate_db.sql:/docker-entrypoint-initdb.d/populate_db.sql
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

networks:
  client: