version: "3.7"
services:
  app:
    build: .
    image: app:dev
    networks:
      - client
    depends_on:
      - db
    environment:
      NODE_ENV: development
    env_file: .env
    volumes:
      - ./app:/app
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    ports:
      - "8080:8080"
    command: npm run dev
  db:
    image: mysql
    networks:
      client:
        aliases:
          - db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    volumes:
      - ./dbdata:/var/lib/mysql
    ports: 
      - "3306:3306"

networks:
  client: